-- renter-service - owns RENTER-role accounts and eventually-consistent local
-- read-models of booking/complaint. This used to be one shared "hostel_one"
-- database with lessor-service; after the split, hostel/room/bed/amenity/
-- invoice/payment/notification all moved out (they belong to lessor-service or
-- notification-service), and booking/complaint here are no longer the source of
-- truth - see Booking.java / Complaint.java for why. This service now gets its
-- own schema ("renter") inside the shared hostel_platform database (see
-- spring.flyway.schemas / currentSchema in application.properties) rather than
-- its own physical database, but the isolation is the same in practice: this
-- service's JDBC connection only ever sees tables inside its own schema.
--
-- users here holds RENTER-role accounts only - lessor-service owns LESSOR
-- accounts in its own schema (see AuthController/RegisterRenterRequest).

CREATE TABLE users (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fname             VARCHAR(255) NOT NULL,
    lname             VARCHAR(255) NOT NULL,
    email             VARCHAR(255) NOT NULL,
    phone_number      VARCHAR(255) NOT NULL,
    password          VARCHAR(255) NOT NULL,
    profilepictureurl VARCHAR(255),
    role              VARCHAR(255) NOT NULL,
    tenant_id         VARCHAR(255) NOT NULL,
    active            BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT uk_users_phone_number UNIQUE (phone_number),
    CONSTRAINT uk_users_password UNIQUE (password)
);

-- Read-model: bed_id/bed_number/room_number/hostel_id/hostel_name are a snapshot
-- (from the client at request time / from lessor-service's decision event), not
-- foreign keys - that data lives in lessor-service's database. booking_ref is the
-- business key used to match this row against lessor-service's authoritative one.
CREATE TABLE booking (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_ref          UUID NOT NULL,
    bed_id               BIGINT NOT NULL,
    bed_number           VARCHAR(255) NOT NULL,
    room_number          VARCHAR(255),
    hostel_id            BIGINT NOT NULL,
    hostel_name          VARCHAR(255) NOT NULL,
    renter_id            BIGINT NOT NULL REFERENCES users (id),
    status               VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    requested_check_in   DATE NOT NULL,
    requested_check_out  DATE,
    created_at           TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    decided_at           TIMESTAMP(6),
    CONSTRAINT uk_booking_ref UNIQUE (booking_ref)
);

-- Read-model, same reasoning as booking above; complaint_ref correlates with
-- lessor-service's authoritative row.
CREATE TABLE complaint (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    complaint_ref   UUID NOT NULL,
    hostel_id       BIGINT NOT NULL,
    hostel_name     VARCHAR(255) NOT NULL,
    raised_by       BIGINT NOT NULL REFERENCES users (id),
    category        VARCHAR(64) NOT NULL,
    description     VARCHAR(1000) NOT NULL,
    status          VARCHAR(32) NOT NULL DEFAULT 'OPEN',
    created_at      TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_complaint_ref UNIQUE (complaint_ref)
);

CREATE TABLE audit_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id    BIGINT,
    action      VARCHAR(128) NOT NULL,
    entity_type VARCHAR(64) NOT NULL,
    entity_id   BIGINT,
    details     VARCHAR(2000),
    created_at  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE refresh_token (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES users (id),
    token_hash VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    revoked    BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_refresh_token_hash UNIQUE (token_hash)
);

CREATE INDEX idx_users_tenant_id ON users (tenant_id);
CREATE INDEX idx_booking_renter ON booking (renter_id);
CREATE INDEX idx_booking_hostel_status ON booking (hostel_id, status);
CREATE INDEX idx_complaint_raised_by ON complaint (raised_by);
CREATE INDEX idx_audit_log_entity ON audit_log (entity_type, entity_id);
CREATE INDEX idx_refresh_token_user ON refresh_token (user_id);
