-- notification-service - owns only this one table. recipient_user_id is a plain
-- column, not a foreign key: the user it refers to lives in lessor-service's or
-- renter-service's database, and this service never queries across that boundary
-- (it only ever receives the id via a Kafka event payload or a validated JWT).

CREATE TABLE notification (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_user_id  BIGINT NOT NULL,
    type               VARCHAR(64) NOT NULL,
    title              VARCHAR(255) NOT NULL,
    body               VARCHAR(1000) NOT NULL,
    created_at         TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    read_at            TIMESTAMP(6)
);

CREATE INDEX idx_notification_recipient ON notification (recipient_user_id, created_at DESC);
