-- lessor-service - owns hostel structure (hostel/floor/room/bed/amenity), billing
-- (invoice/payment), and the authoritative booking/complaint records. This used to
-- be one shared "hostel_one" database with renter-service; after the split each
-- service gets its own schema ("lessor") inside the shared hostel_platform
-- database (see spring.flyway.schemas / currentSchema in application.properties).
-- Cross-schema foreign keys are technically possible in Postgres, but this
-- project deliberately doesn't use them - the whole point of the split is that
-- each service's tables are only ever touched by that service's own JDBC
-- connection, so anything that used to point at a row living in renter-service's
-- data (the renter on a booking, the person who raised a complaint) is now a
-- plain column snapshot taken from the inbound Kafka event, not a FK.
--
-- users here holds LESSOR-role accounts only - renter-service owns RENTER
-- accounts in its own schema. Registration already enforces this split (see
-- AuthController/RegisterLessorRequest), this migration just reflects it.

CREATE TABLE users (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fname             VARCHAR(255) NOT NULL,
    lname             VARCHAR(255) NOT NULL,
    email             VARCHAR(255) NOT NULL,
    phone_number      VARCHAR(255) NOT NULL,
    password          VARCHAR(255) NOT NULL,
    profilepictureurl VARCHAR(255),
    role              VARCHAR(255) NOT NULL,
    tenant_id         VARCHAR(255) NOT NULL,
    active            BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT uk_users_phone_number UNIQUE (phone_number),
    CONSTRAINT uk_users_password UNIQUE (password)
);

-- hostel_address.street / building_name_or_number are encrypted at rest (AES-GCM,
-- application-level JPA converter) - widened for base64 ciphertext overhead.
CREATE TABLE hostel_address (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    building_name_or_number VARCHAR(500),
    street                  VARCHAR(500),
    area                    VARCHAR(255),
    city                    VARCHAR(255),
    state                   VARCHAR(255),
    pin_code                INTEGER
);

-- One hostel per lessor tenant: the lessor experience is scoped to a single hostel,
-- and tenant_id is always derived from the authenticated lessor, never a client header.
CREATE TABLE hostel (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id         VARCHAR(255) NOT NULL,
    name              VARCHAR(255) NOT NULL,
    hostel_address_id BIGINT,
    contact_phone     VARCHAR(255),
    contact_email     VARCHAR(255),
    has_lift          BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_hostel_address_id UNIQUE (hostel_address_id),
    CONSTRAINT uk_hostel_tenant UNIQUE (tenant_id)
);

CREATE TABLE floor (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hostel_id    BIGINT NOT NULL,
    floor_number INTEGER NOT NULL
);

CREATE TABLE room (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hostel_id       BIGINT NOT NULL,
    floor_id        BIGINT NOT NULL,
    room_number     VARCHAR(255) NOT NULL,
    capacity        INTEGER NOT NULL DEFAULT 1,
    monthly_rent    DOUBLE PRECISION NOT NULL,
    sharing_type    INTEGER NOT NULL DEFAULT 1,
    air_conditioned BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE bed (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hostel_id             BIGINT NOT NULL,
    floor_id              BIGINT NOT NULL,
    room_id               BIGINT NOT NULL,
    bed_number            VARCHAR(255) NOT NULL,
    status                VARCHAR(255) NOT NULL DEFAULT 'AVAILABLE',
    check_in_date         DATE,
    check_out_date        DATE,
    next_month_rent_paid  BOOLEAN NOT NULL DEFAULT FALSE,
    maintenance_reason    VARCHAR(255),
    version               BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE amenity (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT uk_amenity_name UNIQUE (name)
);

CREATE TABLE hostel_amenity (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hostel_id  BIGINT NOT NULL,
    amenity_id BIGINT NOT NULL,
    quantity   INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE floor_amenity (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    floor_id   BIGINT NOT NULL,
    amenity_id BIGINT NOT NULL,
    quantity   INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE room_amenity (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id    BIGINT NOT NULL,
    amenity_id BIGINT NOT NULL,
    quantity   INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE invoice (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       VARCHAR(255) NOT NULL,
    hostel_id       BIGINT NOT NULL,
    bed_id          BIGINT NOT NULL,
    total_amount    DOUBLE PRECISION NOT NULL,
    partial_payment DOUBLE PRECISION,
    due_amount      DOUBLE PRECISION,
    status          VARCHAR(255) NOT NULL DEFAULT 'PENDING',
    due_date        DATE,
    created_at      TIMESTAMP(6),
    updated_at      TIMESTAMP(6)
);

-- payment.transaction_id is encrypted at rest (AES-GCM, application-level JPA
-- converter) - widened for base64 ciphertext overhead.
CREATE TABLE payment (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id     BIGINT NOT NULL,
    amount         DOUBLE PRECISION NOT NULL,
    method         VARCHAR(255) NOT NULL,
    transaction_id VARCHAR(500),
    notes          VARCHAR(255),
    payment_date   TIMESTAMP(6) NOT NULL
);

-- renter_id/renter_name/renter_email/renter_phone are a snapshot taken from the
-- BookingRequestedEvent published by renter-service, not a foreign key - the
-- renter's row lives in renter-service's own database. booking_ref is the
-- business key renter-service uses to correlate this row with its own local copy.
CREATE TABLE booking (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_ref          UUID NOT NULL,
    bed_id               BIGINT NOT NULL REFERENCES bed (id),
    renter_id            BIGINT NOT NULL,
    renter_name          VARCHAR(255) NOT NULL,
    renter_email         VARCHAR(255),
    renter_phone         VARCHAR(255),
    status               VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    requested_check_in   DATE NOT NULL,
    requested_check_out  DATE,
    created_at           TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    decided_at           TIMESTAMP(6),
    decided_by           BIGINT REFERENCES users (id),
    version              BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_booking_ref UNIQUE (booking_ref)
);

-- The core defense against double-booking a bed: at most one PENDING or APPROVED
-- booking may exist for a given bed at any time, enforced by Postgres itself so it
-- holds even under concurrent booking-requests events for the same bed. This is
-- exactly why booking lives here rather than in renter-service: the invariant
-- protects bed capacity, which only this database can see.
CREATE UNIQUE INDEX uq_active_booking_per_bed ON booking (bed_id) WHERE status IN ('PENDING', 'APPROVED');

-- raised_by_id/raised_by_name/raised_by_email are a snapshot from the
-- ComplaintRequestedEvent, not a foreign key - same reasoning as booking above.
CREATE TABLE complaint (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    complaint_ref   UUID NOT NULL,
    hostel_id       BIGINT NOT NULL REFERENCES hostel (id),
    raised_by_id    BIGINT NOT NULL,
    raised_by_name  VARCHAR(255) NOT NULL,
    raised_by_email VARCHAR(255),
    category        VARCHAR(64) NOT NULL,
    description     VARCHAR(1000) NOT NULL,
    status          VARCHAR(32) NOT NULL DEFAULT 'OPEN',
    created_at      TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_complaint_ref UNIQUE (complaint_ref)
);

CREATE TABLE audit_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id    BIGINT,
    action      VARCHAR(128) NOT NULL,
    entity_type VARCHAR(64) NOT NULL,
    entity_id   BIGINT,
    details     VARCHAR(2000),
    created_at  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE refresh_token (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES users (id),
    token_hash VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    revoked    BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_refresh_token_hash UNIQUE (token_hash)
);

ALTER TABLE hostel
    ADD CONSTRAINT fk_hostel_address
        FOREIGN KEY (hostel_address_id) REFERENCES hostel_address (id);

ALTER TABLE floor
    ADD CONSTRAINT fk_floor_hostel
        FOREIGN KEY (hostel_id) REFERENCES hostel (id);

ALTER TABLE room
    ADD CONSTRAINT fk_room_hostel
        FOREIGN KEY (hostel_id) REFERENCES hostel (id);

ALTER TABLE room
    ADD CONSTRAINT fk_room_floor
        FOREIGN KEY (floor_id) REFERENCES floor (id);

ALTER TABLE bed
    ADD CONSTRAINT fk_bed_hostel
        FOREIGN KEY (hostel_id) REFERENCES hostel (id);

ALTER TABLE bed
    ADD CONSTRAINT fk_bed_floor
        FOREIGN KEY (floor_id) REFERENCES floor (id);

ALTER TABLE bed
    ADD CONSTRAINT fk_bed_room
        FOREIGN KEY (room_id) REFERENCES room (id);

ALTER TABLE hostel_amenity
    ADD CONSTRAINT fk_hostel_amenity_hostel
        FOREIGN KEY (hostel_id) REFERENCES hostel (id);

ALTER TABLE hostel_amenity
    ADD CONSTRAINT fk_hostel_amenity_amenity
        FOREIGN KEY (amenity_id) REFERENCES amenity (id);

ALTER TABLE floor_amenity
    ADD CONSTRAINT fk_floor_amenity_floor
        FOREIGN KEY (floor_id) REFERENCES floor (id);

ALTER TABLE floor_amenity
    ADD CONSTRAINT fk_floor_amenity_amenity
        FOREIGN KEY (amenity_id) REFERENCES amenity (id);

ALTER TABLE room_amenity
    ADD CONSTRAINT fk_room_amenity_room
        FOREIGN KEY (room_id) REFERENCES room (id);

ALTER TABLE room_amenity
    ADD CONSTRAINT fk_room_amenity_amenity
        FOREIGN KEY (amenity_id) REFERENCES amenity (id);

ALTER TABLE invoice
    ADD CONSTRAINT fk_invoice_hostel
        FOREIGN KEY (hostel_id) REFERENCES hostel (id);

ALTER TABLE invoice
    ADD CONSTRAINT fk_invoice_bed
        FOREIGN KEY (bed_id) REFERENCES bed (id);

ALTER TABLE payment
    ADD CONSTRAINT fk_payment_invoice
        FOREIGN KEY (invoice_id) REFERENCES invoice (id);

CREATE INDEX idx_users_tenant_id ON users (tenant_id);
CREATE INDEX idx_hostel_tenant_id ON hostel (tenant_id);
CREATE INDEX idx_hostel_address_id ON hostel (hostel_address_id);
CREATE INDEX idx_floor_hostel_id ON floor (hostel_id);
CREATE INDEX idx_room_hostel_id ON room (hostel_id);
CREATE INDEX idx_room_floor_id ON room (floor_id);
CREATE INDEX idx_bed_hostel_id ON bed (hostel_id);
CREATE INDEX idx_bed_floor_id ON bed (floor_id);
CREATE INDEX idx_bed_room_id ON bed (room_id);
CREATE INDEX idx_bed_status ON bed (status);
CREATE INDEX idx_hostel_amenity_hostel_id ON hostel_amenity (hostel_id);
CREATE INDEX idx_hostel_amenity_amenity_id ON hostel_amenity (amenity_id);
CREATE INDEX idx_floor_amenity_floor_id ON floor_amenity (floor_id);
CREATE INDEX idx_floor_amenity_amenity_id ON floor_amenity (amenity_id);
CREATE INDEX idx_room_amenity_room_id ON room_amenity (room_id);
CREATE INDEX idx_room_amenity_amenity_id ON room_amenity (amenity_id);
CREATE INDEX idx_invoice_tenant_id ON invoice (tenant_id);
CREATE INDEX idx_invoice_hostel_id ON invoice (hostel_id);
CREATE INDEX idx_invoice_bed_id ON invoice (bed_id);
CREATE INDEX idx_payment_invoice_id ON payment (invoice_id);
CREATE INDEX idx_booking_bed ON booking (bed_id);
CREATE INDEX idx_booking_renter ON booking (renter_id);
CREATE INDEX idx_booking_status ON booking (status);
CREATE INDEX idx_complaint_hostel ON complaint (hostel_id, status);
CREATE INDEX idx_audit_log_entity ON audit_log (entity_type, entity_id);
CREATE INDEX idx_refresh_token_user ON refresh_token (user_id);
